[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://wacel-play.netlify.app"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Access-Control-Allow-Origin = "*"
